### ISSUE TITLE
Crashing XAML designer in VS2012

### ISSUE THREAD

**Issue by igorkulman** [microsoft/rate-my-app#29] opened 2014-01-31 09:27 UTC
When I add the control to a XAML page, the VS2012 designer crashes with

```
InvalidOperationException: The property "FeedbackOverlay.Message" does not expose a get method.
InnerException: None
```

**Comment by bckeller** [comment] 2014-02-05 04:00
Same thing happens to me when I try to look at the properties for the control, then click the miscellaneous dropdown.  I'm using vs 2013.

Also I can't get the ratemyapp to show after n number of app starts.  Maybe has to do with the Feedbackoverlay issue.

**Comment by ltomuta** [comment] 2014-02-06 23:06
This is a strange one. I was able to reproduce the issue by opening the miscellaneous section of the Properties and adding a getter to the Message property fixed the issue. But removing the property again ... did not restore the problem.

So this is easy to "fix", but I hesitate to do it before I understand what really goes on here.

**Comment by ltomuta** [comment] 2014-02-07 00:56
Ok, this should be fixed now. No idea though when the next release will be, so if you find this to be very annoying you will have to make your own build.

**Comment by ltomuta** [comment] 2014-02-07 01:20
@bckeller This was design time issue, should have no impact on how the component behaves at run time.

Can you try using your RMA code in a simple test app? If the problem is reproducible, please share the code with us.

Also, could it be that you are seeing the issue #24 and the component does not work because your app is in trial mode?

**Comment by bckeller** [comment] 2014-02-07 03:49
Just created a new windows phone project and then added RateMyApp via nuget.  The prompt never happened.  The setup of the this app is pretty simple so hopefully I didn't miss something very basic.  Did you want me to send you the solution?  Couldn't find a way to do that here.

**Comment by ltomuta** [comment] 2014-02-08 09:43
@bckeller Your test project works for me although you have placed the component in the wrong position in the page. It must be the last component in the main grid as this will ensure its correct position, on top of all the other UI elements. If you position it inside the "content panel" or other random location, it may be obscured by other UI elements.

```
diff --git a/RMATest/MainPage.xaml b/RMATest/MainPage.xaml
index 5cbdac0..77de32c 100644
--- a/RMATest/MainPage.xaml
+++ b/RMATest/MainPage.xaml
@@ -48,11 +48,7 @@

         <!--ContentPanel - place additional content here-->
         <Grid x:Name="ContentPanel" Grid.Row="1" Margin="12,0,12,0">
-            <controls:FeedbackOverlay x:Name="FeedbackOverlay"
-            Grid.Row="0" Grid.RowSpan="2"
-            FeedbackTo="me@test.com"
-            ApplicationName="MyApp"
-            CompanyName="MyCompany"/>
+
         </Grid>

         <!--Uncomment to see an alignment grid to help ensure your controls are
@@ -62,9 +58,11 @@

             Before shipping remove this XAML and the image itself.-->
         <!--<Image Source="/Assets/AlignmentGrid.png" VerticalAlignment="Top" Height="800" Width="480" Margin="0,-32,0,0" Grid.Row="0" Grid.RowSpan="2" IsHitTestVisible="False" />-->
-
-        
-
+        <controls:FeedbackOverlay x:Name="FeedbackOverlay"
+            Grid.Row="0" Grid.RowSpan="2"
+            FeedbackTo="me@test.com"
+            ApplicationName="MyApp"
+            CompanyName="MyCompany"/>
     </Grid>

 </phone:PhoneApplicationPage>
\ No newline at end of file
```

Also, if you are having problem running this in emulator, do make sure that none of the DLLs from under RMATest\packages\RateMyApp.1.1.0\lib\sl4-wp71 (included localized DLLs) are blocked by Windows as untrusted downloads ( right click the dll file -> Properties -> Security -> unlock if needed)

**Comment by bckeller** [comment] 2014-02-09 14:01
Yea, sorry.  I had moved it around to test it out and see if that helped.  I moved it back to the last component and retested.  Wasn't working in emulator but tried deploying to phone and it works there.  So something in my dev environment.  I also tried seeing about the unlock but when I right clicked - properties - security (windows 8), there wasn't a button to unlock.  So assuming that it's not locked?  I thought I tried deploying to my phone before and it didn't work.  But at least that's working.

Thanks, Brian

**Comment by ltomuta** [comment] 2014-02-09 16:51
Indeed, if no unlock button is visible then the file is not locked (that presuming standard Windows install, on my enterprise configured machine the button is always hidden as the system admins don't want me to unlock untrusted DLLs :) )

If you want to be sure move those files to a FAT formatted thumb drive and then move them back to your PC. The "untrusted" information does not survive on non-NTFS drives and thus once you copy the files back they are trusted and unlocked.

I hope this helps. Meanwhile I think this issue can be closed, start another one if you still see suspicious behaviour.

**Closed as completed by ltomuta** 2014-02-09 16:51 UTC
Labels: bug
